export * from "./axios-client"
export * from "./api-students"
export * from "./api-class"
export * from "./api-provinces"
export * from "./api-participant"
export * from "./api-styleproducts"
export * from "./api-record"
export * from "./api-statusRecord"
export * from "./api-brand"
export * from "./api-patent"
export * from "./apiCopyright"
export *from "./api-lead-provider"